# Generated by Django 4.2.2 on 2024-11-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('PARTICULAR', 'Particular')], default='EMPRESA', max_length=10, verbose_name='Tipo de Cliente')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=100, verbose_name='Nombre Fantasía')),
                ('cuit', models.CharField(max_length=13, unique=True, verbose_name='CUIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rol', models.CharField(choices=[('GERENTE', 'Gerente'), ('JEFE_TALLER', 'Jefe de Taller'), ('ADMINISTRATIVO', 'Administrativo'), ('COMPRAS', 'Encargado de Compras'), ('OTRO', 'Otro')], max_length=20, verbose_name='Rol')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Fijo')),
                ('telefono_celular', models.CharField(max_length=20, verbose_name='Teléfono Celular')),
                ('es_contacto_principal', models.BooleanField(default=False, verbose_name='Contacto Principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Clientes',
                'ordering': ['cliente', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie/PIN')),
                ('numero_serie_motor', models.CharField(max_length=50, verbose_name='Número de Serie Motor')),
                ('año_fabricacion', models.PositiveIntegerField(verbose_name='Año de Fabricación')),
                ('fecha_venta', models.DateField(blank=True, null=True, verbose_name='Fecha de Venta')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja')], default='ACTIVO', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Modelos de Equipos',
                'ordering': ['tipo_equipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Modelo de Motor')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo de Motor',
                'verbose_name_plural': 'Modelos de Motores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHorometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('MANUAL', 'Registro Manual'), ('PRE_ORDER', 'Pre Order'), ('SERVICIO', 'Servicio'), ('API_JD_LINK', 'JD Link API'), ('API_POWER_SIGHT', 'Power Sight API')], max_length=20)),
                ('api_response_id', models.CharField(blank=True, max_length=100, null=True)),
                ('datos_api', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horometro', to='clientes.equipo')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
