# Generated by Django 4.2.2 on 2024-11-04 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('recursosHumanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohorometro',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeloequipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.tipoequipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.modeloequipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo_motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.modelomotor'),
        ),
        migrations.AddField(
            model_name='contactocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['cliente', 'modelo'], name='clientes_eq_cliente_a03bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['numero_serie'], name='clientes_eq_numero__340a9e_idx'),
        ),
    ]
