# Generated by Django 4.2.2 on 2024-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Celular'),
        ),
    ]
