# Generated by Django 4.2.2 on 2024-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_contactocliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ultima_hora_registrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Última Hora Registrada'),
        ),
    ]
