# Generated by Django 4.2.2 on 2025-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_equipo_ultima_hora_registrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo'),
        ),
    ]
