# Generated by Django 4.2.2 on 2025-06-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_contactocliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie_motor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Serie Motor'),
        ),
    ]
