# Generated by Django 4.2.2 on 2025-06-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_equipo_numero_serie_motor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='estado',
        ),
    ]
