# Generated by Django 4.2.2 on 2025-07-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_equipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('EMPRESA', 'Empresa'), ('PARTICULAR', 'Particular'), ('ORGANISMO_PUBLICO', 'Organismo Público')], default='EMPRESA', max_length=20, verbose_name='Tipo de Cliente'),
        ),
    ]
