# Generated by Django 4.2.2 on 2025-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloequipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='modelomotor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Modelo de Motor'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
