# Generated by Django 4.2.2 on 2025-08-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_modeloequipo_nombre_alter_modelomotor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='año_fabricacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fabricación'),
        ),
    ]
