# Generated by Django 4.2.2 on 2024-11-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('facturacion_mano_obra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facturacion_repuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facturacion_asistencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_personal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_operativo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Error')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('subsistema', models.CharField(max_length=100, verbose_name='Subsistema')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Código de Error',
                'verbose_name_plural': 'Códigos de Error',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CostoPersonalTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargas_sociales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vigencia', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIAJE', 'Gastos de Viaje'), ('HOSPEDAJE', 'Hospedaje'), ('COMIDA', 'Comidas'), ('COMBUSTIBLE', 'Combustible'), ('OTROS', 'Otros Gastos')], max_length=20)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('comprobante', models.ImageField(blank=True, upload_to='comprobantes/')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoRepuestosTerceros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('numero_pedido', models.CharField(max_length=50, verbose_name='Número de Pedido')),
                ('fecha_pedido', models.DateField(verbose_name='Fecha de Pedido')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=15)),
                ('descripcion', models.TextField(verbose_name='Descripción del Pedido')),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pedido de Repuestos y Terceros',
                'verbose_name_plural': 'Pedidos de Repuestos y Terceros',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PlanAccion5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no_conforme', models.CharField(max_length=100)),
                ('accion_correctiva', models.TextField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('evidencia_despues', models.ImageField(blank=True, upload_to='5s/despues/')),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan de Acción 5S',
                'verbose_name_plural': 'Planes de Acción 5S',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='PreOrden',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('horometro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horómetro Actual')),
                ('solicitud_cliente', models.TextField(verbose_name='Solicitud del Cliente')),
                ('tiene_problema', models.BooleanField(default=False)),
                ('descripcion_problema', models.TextField(blank=True)),
                ('tipo_trabajo', models.CharField(choices=[('PRESENCIAL_TALLER', 'Presencial en Taller'), ('PRESENCIAL_CAMPO', 'Presencial en Campo'), ('REMOTO', 'Asistencia Remota')], max_length=20)),
                ('fecha_estimada', models.DateField(verbose_name='Fecha Estimada de Atención')),
                ('hora_inicio_estimada', models.TimeField(blank=True, null=True)),
                ('hora_fin_estimada', models.TimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pre Orden',
                'verbose_name_plural': 'Pre Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Revision5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField()),
                ('fecha_proxima', models.DateField()),
                ('bancos_trabajo', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('herramientas_funcionales', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('piezas_organizadas', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('herramientas_devueltas', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('box_limpios', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('sala_garantia', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('piso_limpio', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('instrumentos_limpios', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('paredes_limpias', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('personal_uniformado', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('epp_usado', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('herramientas_calibradas', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('residuos_gestionados', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('documentacion_actualizada', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('procedimientos_seguidos', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=20)),
                ('porcentaje_conformidad', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('evidencias', models.ImageField(blank=True, upload_to='5s/revision/antes/', verbose_name='Evidencias No Conformidades')),
            ],
            options={
                'verbose_name': 'Revisión 5S',
                'verbose_name_plural': 'Revisiones 5S',
                'ordering': ['-fecha_revision'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_servicio', models.DateField(verbose_name='Fecha de Servicio')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('ESPERA_REPUESTOS', 'En Espera de Repuestos'), ('A_FACTURAR', 'Finalizado a Facturar'), ('COMPLETADO', 'Completado')], default='PROGRAMADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('imagen_factura', models.ImageField(blank=True, upload_to='facturas/', verbose_name='Imagen Factura')),
                ('numero_cotizacion', models.CharField(blank=True, max_length=50, verbose_name='Número de Cotización')),
                ('imagen_cotizacion', models.ImageField(blank=True, upload_to='cotizaciones/', verbose_name='Imagen Cotización')),
                ('imagen_informe', models.ImageField(blank=True, upload_to='informes/', verbose_name='Informe de Servicio')),
                ('encuesta_enviada', models.BooleanField(default=False, verbose_name='Encuesta Enviada')),
                ('fecha_envio_encuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Envío Encuesta')),
                ('encuesta_respondida', models.BooleanField(default=False, verbose_name='Encuesta Respondida')),
                ('fecha_respuesta_encuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Respuesta Encuesta')),
                ('puntuacion_encuesta', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puntuación')),
                ('comentarios_encuesta', models.TextField(blank=True, verbose_name='Comentarios Cliente')),
                ('preorden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='servicio', to='gestionDeTaller.preorden')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tmo_estimado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TMO Estimado (horas)')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VentaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código Repuesto')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos', to='gestionDeTaller.servicio')),
            ],
        ),
    ]
