# Generated by Django 4.2.2 on 2024-11-04 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionDeTaller', '0001_initial'),
        ('recursosHumanos', '0001_initial'),
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revision5s',
            name='evaluador',
            field=models.ForeignKey(limit_choices_to={'rol__in': ['GERENTE', 'TECNICO', 'ADMINISTRATIVO']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.sucursal'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='codigos_error',
            field=models.ManyToManyField(blank=True, related_name='preordenes', to='gestionDeTaller.codigoerror', verbose_name='Códigos de Error'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preordenes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preorden',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.equipo'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.sucursal'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='tecnicos',
            field=models.ManyToManyField(limit_choices_to={'rol': 'TECNICO'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preorden',
            name='tipo_problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionDeTaller.tipoproblema'),
        ),
        migrations.AddField(
            model_name='planaccion5s',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planaccion5s',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_accion', to='gestionDeTaller.revision5s'),
        ),
        migrations.AddField(
            model_name='pedidorepuestosterceros',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestionDeTaller.servicio'),
        ),
        migrations.AddField(
            model_name='gastoasistencia',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gestionDeTaller.servicio'),
        ),
        migrations.AddField(
            model_name='costopersonaltaller',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.sucursal'),
        ),
        migrations.AddField(
            model_name='costopersonaltaller',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analisistaller',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.sucursal'),
        ),
    ]
