# Generated by Django 4.2.2 on 2024-11-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='trabajo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('GARANTIA', 'Garantia'), ('PIP', 'Pip'), ('PRE ENTREGA', 'Pre Entrega')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
