# Generated by Django 4.2.2 on 2024-11-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0003_servicio_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
