# Generated by Django 4.2.2 on 2024-11-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0004_servicio_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisistaller',
            options={'verbose_name': 'Analisis de Taller', 'verbose_name_plural': 'Analisis de Taller'},
        ),
        migrations.AlterModelOptions(
            name='costopersonaltaller',
            options={'verbose_name': 'Costo Personal de Taller', 'verbose_name_plural': 'Costos Personal de Taller'},
        ),
    ]
