# Generated by Django 4.2.2 on 2024-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0005_alter_analisistaller_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorden',
            name='horometro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horómetro Actual'),
        ),
    ]
