# Generated by Django 4.2.2 on 2024-11-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0006_alter_preorden_horometro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoProblema',
            new_name='SolicitudTrabajo',
        ),
        migrations.RenameField(
            model_name='preorden',
            old_name='tipo_problema',
            new_name='solicitud_trabajo',
        ),
    ]
