# Generated by Django 4.2.2 on 2024-11-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0007_rename_tipoproblema_solicitudtrabajo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorden',
            old_name='descripcion_problema',
            new_name='detalles_adicionales',
        ),
        migrations.RemoveField(
            model_name='preorden',
            name='tiene_problema',
        ),
    ]
