# Generated by Django 4.2.2 on 2024-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0008_rename_descripcion_problema_preorden_detalles_adicionales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='horometro_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horómetro en Servicio'),
        ),
    ]
