# Generated by Django 4.2.2 on 2024-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0009_servicio_horometro_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='valor_mano_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mano de Obra'),
        ),
    ]
