# Generated by Django 4.2.2 on 2024-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0010_servicio_valor_mano_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen_cotizacion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen_factura',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen_informe',
        ),
        migrations.AddField(
            model_name='servicio',
            name='archivo_cotizacion',
            field=models.FileField(blank=True, help_text='Sube un archivo PDF de la cotización', upload_to='cotizaciones/', verbose_name='Archivo Cotización'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='archivo_factura',
            field=models.FileField(blank=True, help_text='Sube un archivo PDF de la factura', upload_to='facturas/', verbose_name='Archivo Factura'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='archivo_informe',
            field=models.FileField(blank=True, help_text='Sube un archivo PDF del informe', upload_to='informes/', verbose_name='Informe de Servicio'),
        ),
    ]
