# Generated by Django 4.2.2 on 2024-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0011_remove_servicio_imagen_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_envio_documentacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío de Documentación'),
        ),
    ]
