# Generated by Django 4.2.2 on 2024-11-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0012_servicio_fecha_envio_documentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='diagnostico_accion_correctiva',
            field=models.TextField(blank=True, verbose_name='Diagnóstico/Acción Correctiva'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='kilometros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilómetros'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ubicacion',
            field=models.TextField(blank=True, verbose_name='Ubicación'),
        ),
    ]
