# Generated by Django 4.2.2 on 2024-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0013_servicio_diagnostico_accion_correctiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='causa',
            field=models.TextField(blank=True, verbose_name='Causa'),
        ),
    ]
