# Generated by Django 4.2.2 on 2024-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0014_servicio_causa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='diagnostico_accion_correctiva',
        ),
        migrations.AddField(
            model_name='servicio',
            name='accion_correctiva',
            field=models.TextField(blank=True, verbose_name='Acción Correctiva'),
        ),
    ]
