# Generated by Django 4.2.2 on 2024-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0015_remove_servicio_diagnostico_accion_correctiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='firma_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_clientes/', verbose_name='Firma del Cliente'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Cliente'),
        ),
    ]
