# Generated by Django 4.2.2 on 2024-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0016_servicio_firma_cliente_servicio_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorden',
            name='combustible_ingreso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Combustible al Ingreso (%)'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='estado_cabina',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado de la Cabina'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='estado_neumaticos_tren',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado de Neumáticos/Tren Rodante'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='estado_vidrios',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado de los Vidrios'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='firma_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_clientes/', verbose_name='Firma del Cliente'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='imagenes_evidencia',
            field=models.ImageField(blank=True, help_text='Agregue imágenes como evidencia del estado del equipo', null=True, upload_to='evidencia_equipo/', verbose_name='Imágenes de Evidencia'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aclaración del Cliente'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='observaciones_estado_equipo',
            field=models.TextField(blank=True, verbose_name='Observaciones del Estado del Equipo'),
        ),
        migrations.AddField(
            model_name='preorden',
            name='trae_llave',
            field=models.BooleanField(default=False, verbose_name='¿Trae Llave?'),
        ),
    ]
