# Generated by Django 4.2.2 on 2024-11-07 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0017_preorden_combustible_ingreso_preorden_estado_cabina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('preorden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='gestionDeTaller.preorden')),
            ],
        ),
    ]
