# Generated by Django 4.2.2 on 2024-11-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_equipo_ultima_hora_registrada'),
        ('gestionDeTaller', '0018_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorden',
            name='imagenes_evidencia',
        ),
        migrations.CreateModel(
            name='ChecklistSalidaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('Maquinaria', 'Maquinaria'), ('Grupo Electrógeno', 'Grupo Electrógeno'), ('Torre de Iluminación', 'Torre de Iluminación')], max_length=50)),
                ('nivel_aceite_motor', models.BooleanField(default=False, verbose_name='Nivel de Aceite Motor Correcto')),
                ('nivel_refrigerante', models.BooleanField(default=False, verbose_name='Nivel de Refrigerante Correcto')),
                ('nivel_combustible', models.BooleanField(default=False, verbose_name='Nivel de Combustible Correcto')),
                ('estado_neumaticos', models.BooleanField(default=False, verbose_name='Estado de Neumáticos Correcto')),
                ('luces', models.BooleanField(default=False, verbose_name='Luces Funcionando')),
                ('carroceria', models.BooleanField(default=False, verbose_name='Carrocería en Buen Estado')),
                ('preorden', models.BooleanField(default=False, verbose_name='Preorden Confirmada')),
                ('orden_servicio', models.BooleanField(default=False, verbose_name='Orden de Servicio Confirmada')),
                ('herramientas_basicas', models.BooleanField(default=False, verbose_name='Herramientas Básicas Listas')),
                ('herramientas_especiales', models.BooleanField(default=False, verbose_name='Herramientas Especiales Listas')),
                ('repuestos', models.BooleanField(default=False, verbose_name='Repuestos Preparados')),
                ('cobertores', models.BooleanField(default=False, verbose_name='Cobertores Listos')),
                ('tiempo_preparacion', models.DurationField(verbose_name='Tiempo de Preparación (Horas:Minutos)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_salida_campo', to='gestionDeTaller.servicio')),
            ],
        ),
    ]
