# Generated by Django 4.2.2 on 2024-11-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0019_remove_preorden_imagenes_evidencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistsalidacampo',
            name='cliente',
        ),
    ]
