# Generated by Django 4.2.2 on 2024-12-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0020_remove_checklistsalidacampo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorden',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='preorden',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='preordenes_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que crea la Preorden'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preorden',
            name='tecnicos',
            field=models.ManyToManyField(limit_choices_to={'rol': 'TECNICO'}, related_name='preordenes_tecnicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
