# Generated by Django 4.2.2 on 2024-12-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0004_ciudad_provincia'),
        ('gestionDeTaller', '0021_remove_preorden_sucursal_preorden_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorden',
            name='usuario',
        ),
        migrations.AddField(
            model_name='preorden',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.sucursal', verbose_name='Sucursal asociada'),
            preserve_default=False,
        ),
    ]
