# Generated by Django 4.2.2 on 2024-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0022_remove_preorden_usuario_preorden_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorden',
            name='codigos_error',
        ),
        migrations.DeleteModel(
            name='CodigoError',
        ),
        migrations.AddField(
            model_name='preorden',
            name='codigos_error',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
