# Generated by Django 4.2.2 on 2025-03-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0023_remove_preorden_codigos_error_delete_codigoerror_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorden',
            name='clasificacion',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('PROGRAMADO', 'Programado'), ('CAMPAÑA', 'Campaña'), ('ADICIONAL', 'Adicional')], default='SPOT', max_length=20, verbose_name='Clasificación de la Preorden'),
        ),
    ]
