# Generated by Django 4.2.2 on 2025-05-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0024_preorden_clasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='comentarios_encuesta',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='encuesta_enviada',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='encuesta_respondida',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_envio_encuesta',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_respuesta_encuesta',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='puntuacion_encuesta',
        ),
    ]
