# Generated by Django 4.2.2 on 2025-05-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0025_remove_servicio_comentarios_encuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='numero_orden',
        ),
    ]
