# Generated by Django 4.2.2 on 2025-05-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0026_remove_servicio_numero_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorden',
            name='solicitud_trabajo',
        ),
        migrations.DeleteModel(
            name='SolicitudTrabajo',
        ),
    ]
