# Generated by Django 4.2.2 on 2025-05-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0027_remove_preorden_solicitud_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorden',
            name='codigos_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
