# Generated by Django 4.2.2 on 2025-06-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0028_alter_preorden_codigos_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('RESPONDIDA', 'Respondida'), ('NO_RESPONDIDA', 'No Respondida')], default='ENVIADA', max_length=20)),
                ('link_encuesta', models.URLField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='gestionDeTaller.servicio')),
            ],
            options={
                'verbose_name': 'Encuesta de Servicio',
                'verbose_name_plural': 'Encuestas de Servicios',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
