# Generated by Django 4.2.2 on 2025-06-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0029_encuestaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación del 1 al 5')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('nombre_respondente', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_respondente', models.CharField(blank=True, max_length=100, null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='gestionDeTaller.encuestaservicio')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuestas',
            },
        ),
    ]
