# Generated by Django 4.2.2 on 2025-06-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0030_respuestaencuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='calificacion',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Calificación del 0 al 10 (NPS)'),
        ),
    ]
