# Generated by Django 4.2.2 on 2025-06-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0031_alter_respuestaencuesta_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsatisfaccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comunicacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_problema', models.TextField()),
                ('solucion', models.TextField(blank=True, null=True)),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insatisfacciones', to='gestionDeTaller.encuestaservicio')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insatisfacciones_atendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insatisfacción de Cliente',
                'verbose_name_plural': 'Insatisfacciones de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
