# Generated by Django 4.2.2 on 2025-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0032_insatisfaccioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='prioridad',
            field=models.CharField(choices=[('0', 'Urgente'), ('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], default='0', max_length=20),
        ),
    ]
