# Generated by Django 4.2.2 on 2025-06-23 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0033_servicio_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCambioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=50, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=50, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo del Cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_cambios', to='gestionDeTaller.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Cambio de Estado',
                'verbose_name_plural': 'Logs de Cambios de Estado',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['servicio', 'fecha_cambio'], name='gestionDeTa_servici_1ce7b9_idx'), models.Index(fields=['usuario', 'fecha_cambio'], name='gestionDeTa_usuario_6527e9_idx')],
            },
        ),
    ]
