# Generated by Django 4.2.2 on 2025-06-23 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0034_logcambioservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCambioInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo del Cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_cambios_informe', to='gestionDeTaller.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_informe_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Cambio de Informe',
                'verbose_name_plural': 'Logs de Cambios de Informe',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['servicio', 'fecha_cambio'], name='gestionDeTa_servici_ca0230_idx'), models.Index(fields=['usuario', 'fecha_cambio'], name='gestionDeTa_usuario_45a22b_idx')],
            },
        ),
    ]
