# Generated by Django 4.2.2 on 2025-07-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0035_logcambioinforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='trabajo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('GARANTIA', 'Garantia'), ('PIP', 'Pip'), ('PRE ENTREGA', 'Pre Entrega'), ('TRABAJO_INTERNO', 'Trabajo Interno (Ventas Maquinarias)')], max_length=20),
        ),
    ]
