# Generated by Django 4.2.2 on 2025-07-01 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0036_alter_servicio_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_historial', to='gestionDeTaller.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Observación de Servicio',
                'verbose_name_plural': 'Observaciones de Servicios',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['servicio', '-fecha_creacion'], name='gestionDeTa_servici_26f2b7_idx')],
            },
        ),
    ]
