# Generated by Django 4.2.2 on 2025-07-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0037_observacionservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision5s',
            name='evidencias',
        ),
        migrations.CreateModel(
            name='EvidenciaRevision5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='5s/revision/evidencias/', verbose_name='Evidencia')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='gestionDeTaller.revision5s')),
            ],
            options={
                'verbose_name': 'Evidencia de Revisión 5S',
                'verbose_name_plural': 'Evidencias de Revisiones 5S',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
