# Generated by Django 4.2.2 on 2025-07-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0038_remove_revision5s_evidencias_evidenciarevision5s'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaPlanAccion5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='5s/planes/evidencias/', verbose_name='Evidencia')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('plan_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='gestionDeTaller.planaccion5s')),
            ],
            options={
                'verbose_name': 'Evidencia de Plan de Acción 5S',
                'verbose_name_plural': 'Evidencias de Planes de Acción 5S',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
