# Generated by Django 4.2.2 on 2025-07-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0039_evidenciaplanaccion5s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='comentarios_generales',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='cumplimiento_acuerdo',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Calificación del 1 al 10', null=True, verbose_name='Del momento del agendamiento hasta la entrega del Equipo, ¿Lo que fue acordado fue cumplido?'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='motivo_cumplimiento_bajo',
            field=models.TextField(blank=True, null=True, verbose_name='Si la respuesta fue menor o igual a 7, ¿podría decirnos por qué?'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='motivo_recomendacion_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Si la respuesta fue menor o igual a 7, ¿podría decirnos por qué?'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='probabilidad_recomendacion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Calificación del 1 al 10', null=True, verbose_name='En una escala de 1 a 10, ¿cuán probable es que recomiende el Servicio del Concesionario a otras personas?'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='problemas_pendientes',
            field=models.TextField(blank=True, null=True, verbose_name='¿Algún pendiente o problema no resuelto?'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='cargo_respondente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del respondente'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='nombre_respondente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del respondente'),
        ),
    ]
