# Generated by Django 4.2.2 on 2025-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0040_remove_respuestaencuesta_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='orden_servicio',
            field=models.CharField(blank=True, help_text='Número de hasta 8 dígitos de la Orden de Servicio', max_length=8, null=True, verbose_name='OR (Orden de Servicio)'),
        ),
    ]
