# Generated by Django 4.2.2 on 2025-07-10 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0041_servicio_orden_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Repuesto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('categoria', models.CharField(blank=True, help_text='Ej: Filtros, Aceites, Neumáticos, etc.', max_length=100, verbose_name='Categoría')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Almacén')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='gestionDeTa_codigo_ba2fcd_idx'), models.Index(fields=['categoria'], name='gestionDeTa_categor_47fb39_idx'), models.Index(fields=['proveedor'], name='gestionDeTa_proveed_a2d687_idx'), models.Index(fields=['activo'], name='gestionDeTa_activo_2d2b70_idx')],
            },
        ),
    ]
