# Generated by Django 4.2.2 on 2025-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0042_repuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventarepuesto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario'),
        ),
    ]
