# Generated by Django 4.2.2 on 2025-07-11 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0043_alter_ventarepuesto_costo_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='herramientas_especiales/', verbose_name='Foto')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Herramienta Especial',
                'verbose_name_plural': 'Herramientas Especiales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ReservaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('RETIRADA', 'Retirada'), ('DEVUELTA', 'Devuelta'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado')),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestionDeTaller.herramientaespecial', verbose_name='Herramienta')),
                ('preorden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDeTaller.preorden', verbose_name='Pre-Orden')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDeTaller.servicio', verbose_name='Servicio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva de Herramienta',
                'verbose_name_plural': 'Reservas de Herramientas',
                'ordering': ['-fecha_reserva', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('RESERVA', 'Reserva'), ('RETIRO', 'Retiro'), ('DEVOLUCION', 'Devolución'), ('CANCELACION', 'Cancelación')], max_length=20, verbose_name='Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gestionDeTaller.herramientaespecial', verbose_name='Herramienta')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDeTaller.reservaherramienta', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Herramienta',
                'verbose_name_plural': 'Logs de Herramientas',
                'ordering': ['-fecha'],
            },
        ),
    ]
