# Generated by Django 4.2.2 on 2025-07-11 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0044_herramientaespecial_reservaherramienta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaHerramientaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateField(verbose_name='Fecha de Auditoría')),
                ('tipo_auditoria', models.CharField(choices=[('SEMESTRAL', 'Semestral'), ('EXTRAORDINARIA', 'Extraordinaria'), ('DEVOLUCION', 'Devolución'), ('VENCIMIENTO', 'Vencimiento')], max_length=20, verbose_name='Tipo de Auditoría')),
                ('estado_general', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, verbose_name='Estado General')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_herramientas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Auditoría de Herramientas Personales',
                'verbose_name_plural': 'Auditorías de Herramientas Personales',
                'ordering': ['-fecha_auditoria', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HerramientaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('CAJA_HERRAMIENTAS', 'Caja de Herramientas'), ('TESTER', 'Tester/Multímetro'), ('HERRAMIENTA_ADICIONAL', 'Herramienta Adicional'), ('EPP', 'Elemento de Protección Personal')], max_length=30, verbose_name='Categoría')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('costo_reposicion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Reposición')),
                ('vida_util_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vida Útil (meses)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_personales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Herramienta Personal',
                'verbose_name_plural': 'Herramientas Personales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAuditoriaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_herramienta', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('DAÑADA', 'Dañada'), ('DESGASTADA', 'Desgastada'), ('VENCIDA', 'Vencida')], max_length=20, verbose_name='Estado de la Herramienta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('accion_requerida', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('REPOSICION', 'Reposición'), ('REPARACION', 'Reparación'), ('LIMPIEZA', 'Limpieza'), ('MANTENIMIENTO', 'Mantenimiento')], default='NINGUNA', max_length=20, verbose_name='Acción Requerida')),
                ('fecha_limite_accion', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Acción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_auditoria', to='gestionDeTaller.auditoriaherramientapersonal', verbose_name='Auditoría')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDeTaller.herramientapersonal', verbose_name='Herramienta')),
            ],
            options={
                'verbose_name': 'Detalle de Auditoría de Herramienta',
                'verbose_name_plural': 'Detalles de Auditorías de Herramientas',
                'ordering': ['auditoria', 'herramienta__categoria', 'herramienta__nombre'],
                'unique_together': {('auditoria', 'herramienta')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionHerramientaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('estado_asignacion', models.CharField(choices=[('ENTREGADA', 'Entregada'), ('DEVUELTA', 'Devuelta'), ('PERDIDA', 'Perdida'), ('DAÑADA', 'Dañada'), ('VENCIDA', 'Vencida')], default='ENTREGADA', max_length=20, verbose_name='Estado')),
                ('observaciones_asignacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestionDeTaller.herramientapersonal', verbose_name='Herramienta')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_herramientas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Asignación de Herramienta Personal',
                'verbose_name_plural': 'Asignaciones de Herramientas Personales',
                'ordering': ['-fecha_asignacion', '-fecha_creacion'],
                'unique_together': {('tecnico', 'herramienta', 'estado_asignacion')},
            },
        ),
    ]
