# Generated by Django 4.2.2 on 2025-07-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0045_auditoriaherramientapersonal_herramientapersonal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientapersonal',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADA', 'Asignada'), ('MANTENIMIENTO', 'Mantenimiento'), ('PERDIDA', 'Perdida'), ('DAÑADA', 'Dañada'), ('VENCIDA', 'Vencida')], default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
