# Generated by Django 4.2.2 on 2025-07-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0046_herramientapersonal_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientapersonal',
            name='fecha_certificacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Certificación'),
        ),
        migrations.AddField(
            model_name='herramientapersonal',
            name='fecha_vencimiento_certificacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento de Certificación'),
        ),
    ]
