# Generated by Django 4.2.2 on 2025-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0047_herramientapersonal_fecha_certificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionherramientapersonal',
            name='observaciones_devolucion',
            field=models.TextField(blank=True, verbose_name='Observaciones de Devolución'),
        ),
    ]
