# Generated by Django 4.2.2 on 2025-07-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0048_asignacionherramientapersonal_observaciones_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionherramientapersonal',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
    ]
