# Generated by Django 4.2.2 on 2025-07-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0049_asignacionherramientapersonal_fecha_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHerramientaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Item')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('DAÑADO', 'Dañado'), ('DESGASTADO', 'Desgastado'), ('VENCIDO', 'Vencido')], default='PRESENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestionDeTaller.herramientapersonal', verbose_name='Herramienta')),
            ],
            options={
                'verbose_name': 'Item de Herramienta Personal',
                'verbose_name_plural': 'Items de Herramientas Personales',
                'ordering': ['herramienta', 'nombre'],
                'unique_together': {('herramienta', 'nombre')},
            },
        ),
    ]
