# Generated by Django 4.2.2 on 2025-07-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0050_itemherramientapersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCambioItemHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_items', to='gestionDeTaller.auditoriaherramientapersonal', verbose_name='Auditoría')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_cambios', to='gestionDeTaller.itemherramientapersonal', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Log de Cambio de Item',
                'verbose_name_plural': 'Logs de Cambios de Items',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
