# Generated by Django 4.2.2 on 2025-07-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0051_logcambioitemherramienta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision5s',
            name='bancos_trabajo',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='box_limpios',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='epp_usado',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='herramientas_calibradas',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='herramientas_devueltas',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='herramientas_funcionales',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='instrumentos_limpios',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='paredes_limpias',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='personal_uniformado',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='piezas_organizadas',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='piso_limpio',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='sala_garantia',
        ),
        migrations.AddField(
            model_name='revision5s',
            name='area_trabajo_limpia',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='El área de trabajo se mantiene limpia y ordenada durante las operaciones'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='box_trabajo_limpios',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Box de trabajo están limpios, sin aceite en el piso, ordenados, sin elementos en el piso'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='capacitacion_actualizada',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='El personal cuenta con la capacitación actualizada en procedimientos de seguridad y calidad'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='epp_correspondiente_usado',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Se están usando los EPP correspondientes en los trabajos en curso y todos tienen el uniforme correspondiente'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='herramientas_calibradas_certificadas',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Todas las herramientas se encuentran calibradas y certificadas (las que correspondan)'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='herramientas_no_uso_limpias',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Las herramientas de uso común o especiales que no se están usando en un trabajo en curso se encuentran limpias'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='herramientas_uso_comun_devueltas',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Las herramientas de uso común o especiales han sido devueltas (sin contar las que se estén usando en un trabajo en curso)'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='mantenimiento_preventivo',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='El mantenimiento preventivo de equipos y herramientas se realiza según el cronograma establecido'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='mejora_continua',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Se identifican y documentan oportunidades de mejora en los procesos de trabajo'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='mesas_trabajo_estaticas',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Mesas de trabajo estáticas están limpias, sin elementos ajenos a un trabajo en curso'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='paredes_limpias_tachos_ok',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Las paredes están limpias y los tachos de basura están ok (si están llenos y no se sacó la basura está mal)'),
        ),
        migrations.AddField(
            model_name='revision5s',
            name='sala_garantia_ordenada',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Sala de garantía se encuentra ordenada y con los elementos e información que corresponde según los procedimientos'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='documentacion_actualizada',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='La documentación técnica y procedimental está actualizada y accesible'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='procedimientos_seguidos',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Los procedimientos de trabajo se siguen correctamente según los estándares establecidos'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='residuos_gestionados',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Los residuos se gestionan correctamente según los procedimientos de reciclaje y disposición'),
        ),
    ]
