# Generated by Django 4.2.2 on 2025-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0052_remove_revision5s_bancos_trabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision5s',
            name='area_trabajo_limpia',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='capacitacion_actualizada',
        ),
        migrations.RemoveField(
            model_name='revision5s',
            name='documentacion_actualizada',
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='box_trabajo_limpios',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Box de trabajo están limpios, sin aceite, ordenados y sin elementos en el piso'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='herramientas_no_uso_limpias',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Las herramientas de uso común o especiales que no se están usando en un trabajo en curso se encuentran limpias y devueltas'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='paredes_limpias_tachos_ok',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Las paredes están limpias y los cestos de basura estan siendo vaciados segun corresponda'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='residuos_gestionados',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Los residuos depositados afuera del taller se gestionan correctamente según los procedimientos de reciclaje y disposición'),
        ),
    ]
