# Generated by Django 4.2.2 on 2025-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0053_remove_revision5s_area_trabajo_limpia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision5s',
            name='herramientas_no_uso_limpias',
        ),
        migrations.AddField(
            model_name='revision5s',
            name='zona_repuestos_ordenada',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='La zona de repuestos dentro del taller se encuentra ordenada, identificada y con elementos correctamente ubicados'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='herramientas_uso_comun_devueltas',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Las herramientas de uso común o especiales han sido devueltas y se encuentran limpias (sin contar las que se estén usando en un trabajo en curso)'),
        ),
        migrations.AlterField(
            model_name='revision5s',
            name='paredes_limpias_tachos_ok',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], default='CONFORME', max_length=20, verbose_name='Las paredes están limpias y los cestos de basura están siendo vaciados según corresponda'),
        ),
    ]
