# Generated by Django 4.2.2 on 2025-07-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0054_remove_revision5s_herramientas_no_uso_limpias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaccion5s',
            name='item_no_conforme',
            field=models.TextField(),
        ),
    ]
