# Generated by Django 4.2.2 on 2025-07-26 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0055_alter_planaccion5s_item_no_conforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlanAccion5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no_conforme', models.CharField(max_length=200, verbose_name='Item No Conforme')),
                ('comentario_correccion', models.TextField(help_text='Cómo se va a corregir este desvío', verbose_name='Comentario de Corrección')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('evidencia_foto', models.ImageField(blank=True, null=True, upload_to='5s/items/evidencias/', verbose_name='Evidencia Foto')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('plan_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestionDeTaller.planaccion5s')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Item de Plan de Acción 5S',
                'verbose_name_plural': 'Items de Planes de Acción 5S',
                'ordering': ['fecha_limite', 'item_no_conforme'],
            },
        ),
    ]
