# Generated by Django 4.2.2 on 2025-08-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0056_itemplanaccion5s'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaRepuestosSimplificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de Repuestos')),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total (USD)')),
                ('fecha_venta', models.DateField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venta_repuestos_simplificada', to='gestionDeTaller.servicio')),
            ],
            options={
                'verbose_name': 'Venta de Repuestos Simplificada',
                'verbose_name_plural': 'Ventas de Repuestos Simplificadas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='GastoInsumosTerceros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Gasto')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (USD)')),
                ('fecha_gasto', models.DateField(auto_now_add=True, verbose_name='Fecha del Gasto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_insumos_terceros', to='gestionDeTaller.servicio')),
            ],
            options={
                'verbose_name': 'Gasto de Insumos/Terceros',
                'verbose_name_plural': 'Gastos de Insumos/Terceros',
                'ordering': ['-fecha_gasto'],
            },
        ),
        migrations.CreateModel(
            name='GastoAsistenciaSimplificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Gasto')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (USD)')),
                ('fecha_gasto', models.DateField(auto_now_add=True, verbose_name='Fecha del Gasto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_asistencia_simplificados', to='gestionDeTaller.servicio')),
            ],
            options={
                'verbose_name': 'Gasto de Asistencia Simplificado',
                'verbose_name_plural': 'Gastos de Asistencia Simplificados',
                'ordering': ['-fecha_gasto'],
            },
        ),
    ]
