# Generated by Django 4.2.2 on 2025-08-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0057_ventarepuestossimplificada_gastoinsumosterceros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('ESPERA_REPUESTOS', 'En Espera de Repuestos'), ('ESPERA_CONFIRMACION_CLIENTE', 'En Espera Confirmación Cliente'), ('A_FACTURAR', 'Finalizado a Facturar'), ('COMPLETADO', 'Completado')], default='PROGRAMADO', max_length=30),
        ),
    ]
