# Generated by Django 4.2.2 on 2025-08-07 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0058_alter_servicio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='gestionDeTaller.tipoequipo')),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Modelos de Equipos',
                'ordering': ['tipo_equipo', 'nombre'],
                'unique_together': {('tipo_equipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modelo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifarios', to='gestionDeTaller.modeloequipo')),
            ],
            options={
                'verbose_name': 'Tarifario',
                'verbose_name_plural': 'Tarifarios',
                'ordering': ['modelo_equipo__tipo_equipo', 'modelo_equipo', 'nombre_servicio'],
                'unique_together': {('modelo_equipo', 'nombre_servicio')},
            },
        ),
    ]
