# Generated by Django 4.2.2 on 2025-08-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_modeloequipo_nombre_alter_modelomotor_nombre_and_more'),
        ('gestionDeTaller', '0059_tipoequipo_modeloequipo_tarifario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifario',
            name='modelo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifarios', to='clientes.modeloequipo'),
        ),
        migrations.DeleteModel(
            name='ModeloEquipo',
        ),
        migrations.DeleteModel(
            name='TipoEquipo',
        ),
    ]
