# Generated by Django 4.2.2 on 2025-08-07 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_modeloequipo_nombre_alter_modelomotor_nombre_and_more'),
        ('gestionDeTaller', '0060_alter_tarifario_modelo_equipo_delete_modeloequipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifario',
            options={'ordering': ['fecha', 'nombre_servicio'], 'verbose_name': 'Tarifario', 'verbose_name_plural': 'Tarifarios'},
        ),
        migrations.AlterUniqueTogether(
            name='tarifario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='tarifario',
            name='modelo_equipo',
        ),
        migrations.CreateModel(
            name='TarifarioModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifarios_relacionados', to='clientes.modeloequipo')),
                ('tarifario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_equipo', to='gestionDeTaller.tarifario')),
            ],
            options={
                'verbose_name': 'Tarifario - Modelo de Equipo',
                'verbose_name_plural': 'Tarifarios - Modelos de Equipo',
                'unique_together': {('tarifario', 'modelo_equipo')},
            },
        ),
    ]
