# Generated by Django 4.2.2 on 2025-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0062_alter_servicio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifario',
            name='actividades',
            field=models.TextField(blank=True, help_text='Lista de actividades que incluye este servicio', verbose_name='Actividades Incluidas'),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='tmo_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado que lleva realizar este servicio', max_digits=5, null=True, verbose_name='TMO (Tiempo Medio Operativo) en Horas'),
        ),
    ]
