# Generated by Django 4.2.2 on 2025-08-08 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_modeloequipo_nombre_alter_modelomotor_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionDeTaller', '0063_tarifario_actividades_tarifario_tmo_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateField(verbose_name='Fecha de Inspección')),
                ('horometro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horómetro')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADO', 'Completado'), ('ENVIADO', 'Enviado al Cliente')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('notas_generales', models.TextField(blank=True, verbose_name='Notas Generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.equipo', verbose_name='Equipo Inspeccionado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_inspeccion', to='gestionDeTaller.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Checklist de Inspección',
                'verbose_name_plural': 'Checklists de Inspección',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogChecklistInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('detalles', models.TextField(blank=True, verbose_name='Detalles')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_cambios', to='gestionDeTaller.checklistinspeccion', verbose_name='Checklist')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Checklist de Inspección',
                'verbose_name_plural': 'Logs de Checklists de Inspección',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='ElementoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('CABINA', 'Cabina'), ('TRANSMISSION', 'Transmission'), ('SISTEMA_HIDRAULICO', 'Sistema Hidráulico'), ('SISTEMA_ELECTRICO', 'Sistema Eléctrico'), ('SISTEMA_FRENOS', 'Sistema de Frenos'), ('MOTOR', 'Motor'), ('CHASSIS_ESTRUCTURA', 'Chassis y Estructura'), ('SISTEMA_ASPIRACION', 'Sistema de Aspiración'), ('SISTEMA_COMBUSTIBLE', 'Sistema de Combustible'), ('SISTEMA_DEF', 'Sistema DEF'), ('SISTEMA_REFRIGERACION', 'Sistema de Refrigeración'), ('LANTAS_CARRILERIA', 'Lantas y Carrilería')], max_length=30, verbose_name='Sección')),
                ('nombre_elemento', models.CharField(max_length=200, verbose_name='Elemento de Verificación')),
                ('respuesta', models.CharField(blank=True, choices=[('A', 'Aceptable'), ('R', 'Rechazado'), ('N/A', 'No Aplica')], max_length=3, verbose_name='Respuesta')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='gestionDeTaller.checklistinspeccion', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Elemento de Checklist',
                'verbose_name_plural': 'Elementos de Checklist',
                'ordering': ['seccion', 'orden', 'nombre_elemento'],
                'unique_together': {('checklist', 'nombre_elemento')},
            },
        ),
    ]
