# Generated by Django 4.2.2 on 2025-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0064_checklistinspeccion_logchecklistinspeccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementochecklist',
            name='seccion',
            field=models.CharField(choices=[('CABINA', 'Cabina'), ('TRANSMISSION', 'Transmission'), ('SISTEMA_FRENOS', 'Sistema de Frenos'), ('MOTOR', 'Motor'), ('SISTEMA_REFRIGERACION', 'Sistema de Refrigeración'), ('LANTAS_CARRILERIA', 'Llantas y Carrilería'), ('SISTEMA_HIDRAULICO', 'Sistema Hidráulico'), ('SISTEMA_ELECTRICO', 'Sistema Eléctrico'), ('CHASSIS_ESTRUCTURA', 'Chassis y Estructura')], max_length=30, verbose_name='Sección'),
        ),
    ]
