# Generated by Django 4.2.2 on 2025-06-26 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0007_remove_equipo_estado'),
        ('recursosHumanos', '0013_remove_actividadtrabajo_categoria_facturacion_destinatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('pin_equipo', models.CharField(max_length=50, verbose_name='PIN del Equipo')),
                ('clasificacion', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10, verbose_name='Clasificación')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de Alerta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada a Técnico'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('observaciones_tecnico', models.TextField(blank=True, verbose_name='Observaciones del Técnico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.sucursal', verbose_name='Sucursal')),
                ('tecnico_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Alerta de Equipo',
                'verbose_name_plural': 'Alertas de Equipos',
                'ordering': ['-fecha', '-clasificacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la Asignación')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroSoluciones.alertaequipo', verbose_name='Alerta')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'TECNICO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Asignación de Alerta',
                'verbose_name_plural': 'Asignaciones de Alertas',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='LeadJohnDeere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('tipo_clasificacion', models.CharField(max_length=50, verbose_name='Tipo/Clasificación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('CALIFICADO', 'Calificado'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], default='NUEVO', max_length=15, verbose_name='Estado')),
                ('fecha_contacto', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Primer Contacto')),
                ('observaciones_contacto', models.TextField(blank=True, verbose_name='Observaciones del Contacto')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Estimado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.equipo', verbose_name='Equipo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Lead John Deere',
                'verbose_name_plural': 'Leads John Deere',
                'ordering': ['-fecha', 'estado'],
                'indexes': [models.Index(fields=['estado', 'fecha'], name='centroSoluc_estado_fd015c_idx'), models.Index(fields=['cliente', 'equipo'], name='centroSoluc_cliente_a77f43_idx'), models.Index(fields=['sucursal', 'estado'], name='centroSoluc_sucursa_5cd0dc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alertaequipo',
            index=models.Index(fields=['estado', 'clasificacion'], name='centroSoluc_estado_36aa19_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaequipo',
            index=models.Index(fields=['cliente', 'fecha'], name='centroSoluc_cliente_5729dd_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaequipo',
            index=models.Index(fields=['tecnico_asignado', 'estado'], name='centroSoluc_tecnico_3cd31c_idx'),
        ),
    ]
