# Generated by Django 4.2.2 on 2025-07-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroSoluciones', '0002_auto_20250627_1301'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadjohndeere',
            new_name='centroSoluc_clasifi_1c4b4d_idx',
            old_name='centroSoluc_clasifi_123456_idx',
        ),
    ]
