# Generated by Django 4.2.2 on 2025-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroSoluciones', '0003_rename_centrosoluc_clasifi_123456_idx_centrosoluc_clasifi_1c4b4d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaequipo',
            name='conexion_sar_realizada',
            field=models.BooleanField(default=False, verbose_name='Conexión SAR Realizada'),
        ),
        migrations.AddField(
            model_name='alertaequipo',
            name='fecha_conexion_sar',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Conexión SAR'),
        ),
        migrations.AddField(
            model_name='alertaequipo',
            name='oportunidad_crm_creada',
            field=models.BooleanField(default=False, verbose_name='Oportunidad CRM Creada'),
        ),
        migrations.AddField(
            model_name='alertaequipo',
            name='resultado_conexion_sar',
            field=models.TextField(blank=True, verbose_name='Resultado de Conexión SAR'),
        ),
    ]
