# Generated by Django 4.2.2 on 2025-07-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centroSoluciones', '0004_alertaequipo_conexion_sar_realizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Alerta')),
                ('modelo_equipo', models.CharField(max_length=100, verbose_name='Modelo de Equipo')),
                ('descripcion', models.TextField(verbose_name='Descripción del Código')),
                ('clasificacion', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10, verbose_name='Clasificación por Defecto')),
                ('instrucciones_resolucion', models.TextField(blank=True, help_text='Pasos recomendados para resolver este tipo de alerta', verbose_name='Instrucciones de Resolución')),
                ('repuestos_comunes', models.TextField(blank=True, help_text='Repuestos que suelen necesitarse para este tipo de alerta', verbose_name='Repuestos Comunes')),
                ('tiempo_estimado_resolucion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo Estimado de Resolución (horas)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_alerta_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Código de Alerta',
                'verbose_name_plural': 'Códigos de Alerta',
                'ordering': ['codigo', 'modelo_equipo'],
                'indexes': [models.Index(fields=['codigo'], name='centroSoluc_codigo_c6dbff_idx'), models.Index(fields=['modelo_equipo'], name='centroSoluc_modelo__b65126_idx'), models.Index(fields=['clasificacion'], name='centroSoluc_clasifi_cceab9_idx'), models.Index(fields=['activo'], name='centroSoluc_activo_5fc29f_idx')],
            },
        ),
    ]
