# Generated by Django 4.2.2 on 2025-08-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0010_alter_equipo_año_fabricacion'),
        ('centroSoluciones', '0005_codigoalerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reporte', models.DateField(help_text='Fecha extraída del nombre del archivo CSV')),
                ('archivo_csv', models.FileField(help_text='Archivo CSV original', upload_to='reportes_csc/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'Generado'), ('ENVIADO', 'Enviado')], default='BORRADOR', max_length=20)),
                ('recomendaciones_automaticas', models.TextField(blank=True, help_text='Recomendaciones generadas automáticamente')),
                ('comentarios_manuales', models.TextField(blank=True, help_text='Comentarios adicionales del usuario')),
                ('total_horas_analizadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eficiencia_general', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de eficiencia', max_digits=5, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_csc', to='clientes.equipo')),
            ],
            options={
                'verbose_name': 'Reporte CSC',
                'verbose_name_plural': 'Reportes CSC',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='DatosReporteCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ej: Utilización del motor, MFWD Utilization per gear', max_length=100)),
                ('serie', models.CharField(help_text='Ej: Carga baja, Activado - F1', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(help_text='hr, %, etc.', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='centroSoluciones.reportecsc')),
            ],
            options={
                'verbose_name': 'Dato Reporte CSC',
                'verbose_name_plural': 'Datos Reporte CSC',
                'unique_together': {('reporte', 'categoria', 'serie')},
            },
        ),
    ]
