# Generated by Django 4.2.2 on 2025-08-12 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centroSoluciones', '0006_reportecsc_datosreportecsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaReporteCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('MEDIANA', 'Mediana'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10, verbose_name='Severidad')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Alerta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción adicional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='centroSoluciones.reportecsc')),
            ],
            options={
                'verbose_name': 'Alerta Reporte CSC',
                'verbose_name_plural': 'Alertas Reporte CSC',
                'ordering': ['-fecha_hora', '-severidad'],
            },
        ),
    ]
