# Generated by Django 4.2.2 on 2025-08-15 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centroSoluciones', '0007_alertareportecsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('archivo_id', models.IntegerField()),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('organizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_reporte', models.CharField(choices=[('FLOTA', 'Reporte de Flota'), ('ORGANIZACION', 'Reporte de Organización'), ('INDIVIDUAL', 'Reporte Individual')], max_length=20)),
                ('equipo_id', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
