# Generated by Django 4.2.2 on 2025-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroSoluciones', '0008_reportepublico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportepublico',
            name='tipo_reporte',
            field=models.CharField(choices=[('FLOTA', 'Reporte de Flota'), ('ORGANIZACION', 'Reporte de Organización'), ('INDIVIDUAL', 'Reporte Individual'), ('CSC', 'Reporte CSC')], max_length=20),
        ),
    ]
