# Generated by Django 4.2.2 on 2025-08-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centroSoluciones', '0008_archivodatosmensual_notificacionmensual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertareportecsc',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='alertareportecsc',
            name='reporte',
        ),
        migrations.AlterUniqueTogether(
            name='datosreportecsc',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='datosreportecsc',
            name='reporte',
        ),
        migrations.RemoveField(
            model_name='reportecsc',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='reportecsc',
            name='equipo',
        ),
        migrations.RemoveIndex(
            model_name='notificacionmensual',
            name='centroSoluc_resuelt_0cb250_idx',
        ),
        migrations.RemoveField(
            model_name='notificacionmensual',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='notificacionmensual',
            name='resuelta_por',
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='archivo',
            field=models.FileField(upload_to='archivos_mensuales/', verbose_name='Archivo Excel'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='cargado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='errores',
            field=models.TextField(blank=True, verbose_name='Errores de procesamiento'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='log_procesamiento',
            field=models.TextField(blank=True, verbose_name='Log de procesamiento'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='nombre_archivo',
            field=models.CharField(max_length=255, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Período analizado'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='registros_procesados',
            field=models.IntegerField(default=0, verbose_name='Registros procesados'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='tipo',
            field=models.CharField(choices=[('UTILIZACION', 'Datos de Utilización'), ('NOTIFICACIONES', 'Notificaciones y Alertas')], max_length=20, verbose_name='Tipo de archivo'),
        ),
        migrations.AlterField(
            model_name='archivodatosmensual',
            name='total_registros',
            field=models.IntegerField(default=0, verbose_name='Total de registros'),
        ),
        migrations.AlterField(
            model_name='notificacionmensual',
            name='codigos_diagnostico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacionmensual',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificacionmensual',
            name='incidencias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacionmensual',
            name='resuelta',
            field=models.BooleanField(default=False, verbose_name='Resuelta'),
        ),
        migrations.AlterField(
            model_name='notificacionmensual',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='AlertaReporteCSC',
        ),
        migrations.DeleteModel(
            name='DatosReporteCSC',
        ),
        migrations.DeleteModel(
            name='ReporteCSC',
        ),
    ]
