# Generated by Django 4.2.2 on 2025-07-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionDeTaller', '0040_remove_respuestaencuesta_calificacion_and_more'),
        ('clientes', '0009_alter_modeloequipo_nombre_alter_modelomotor_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100, unique=True, verbose_name='Machine ID')),
                ('equipment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipment ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo')),
                ('make_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('last_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Última Latitud')),
                ('last_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Última Longitud')),
                ('last_location_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Última Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_oc', to='clientes.equipo', verbose_name='Equipo Local')),
            ],
            options={
                'verbose_name': 'Máquina Operations Center',
                'verbose_name_plural': 'Máquinas Operations Center',
                'ordering': ['-last_sync'],
            },
        ),
        migrations.CreateModel(
            name='OperationsCenterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=200, verbose_name='Client Secret')),
                ('redirect_uri', models.URLField(verbose_name='Redirect URI')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At')),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Operations Center',
                'verbose_name_plural': 'Configuraciones Operations Center',
            },
        ),
        migrations.CreateModel(
            name='TelemetryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Tipo de Reporte')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('GENERATED', 'Generado'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='telemetry_reports/', verbose_name='Archivo del Reporte')),
                ('sent_to', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Enviado a')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('include_location', models.BooleanField(default=True, verbose_name='Incluir Ubicación')),
                ('include_hours', models.BooleanField(default=True, verbose_name='Incluir Horas')),
                ('include_alerts', models.BooleanField(default=True, verbose_name='Incluir Alertas')),
                ('include_usage', models.BooleanField(default=True, verbose_name='Incluir Uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_reports', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Reporte de Telemetría',
                'verbose_name_plural': 'Reportes de Telemetría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReportMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas Totales')),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distancia Total')),
                ('alerts_count', models.IntegerField(default=0, verbose_name='Cantidad de Alertas')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Consumo de Combustible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_reports', to='operationsCenter.machine')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='operationsCenter.telemetryreport')),
            ],
            options={
                'verbose_name': 'Máquina en Reporte',
                'verbose_name_plural': 'Máquinas en Reportes',
                'unique_together': {('report', 'machine')},
            },
        ),
        migrations.CreateModel(
            name='MachineLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altitud')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Velocidad')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='operationsCenter.machine')),
            ],
            options={
                'verbose_name': 'Ubicación de Máquina',
                'verbose_name_plural': 'Ubicaciones de Máquinas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', '-timestamp'], name='operationsC_machine_becfd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachineHoursOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('hours_of_operation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas de Operación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_of_operation', to='operationsCenter.machine')),
            ],
            options={
                'verbose_name': 'Horas de Operación',
                'verbose_name_plural': 'Horas de Operación',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', '-timestamp'], name='operationsC_machine_380568_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachineEngineHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('engine_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas de Motor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_hours', to='operationsCenter.machine')),
            ],
            options={
                'verbose_name': 'Horas de Motor',
                'verbose_name_plural': 'Horas de Motor',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', '-timestamp'], name='operationsC_machine_acac5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachineAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100, unique=True, verbose_name='Alert ID')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('ACKNOWLEDGED', 'Reconocida'), ('RESOLVED', 'Resuelta'), ('CLEARED', 'Limpiada')], max_length=20, verbose_name='Estado')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconocida en')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='operationsCenter.machine')),
                ('servicio_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDeTaller.servicio', verbose_name='Servicio Relacionado')),
            ],
            options={
                'verbose_name': 'Alerta de Máquina',
                'verbose_name_plural': 'Alertas de Máquinas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', '-timestamp'], name='operationsC_machine_1de636_idx'), models.Index(fields=['status', '-timestamp'], name='operationsC_status_a69985_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceStateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('device_state', models.CharField(max_length=50, verbose_name='Estado del Dispositivo')),
                ('signal_strength', models.IntegerField(blank=True, null=True, verbose_name='Intensidad de Señal')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='Nivel de Batería')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_reports', to='operationsCenter.machine')),
            ],
            options={
                'verbose_name': 'Reporte de Estado de Dispositivo',
                'verbose_name_plural': 'Reportes de Estado de Dispositivos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', '-timestamp'], name='operationsC_machine_f8bdfe_idx')],
            },
        ),
    ]
