# Generated by Django 4.2.2 on 2025-07-08 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_alter_modeloequipo_nombre_alter_modelomotor_nombre_and_more'),
        ('recursosHumanos', '0013_remove_actividadtrabajo_categoria_facturacion_destinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Certificado')),
                ('tipo', models.CharField(choices=[('GARANTIA', 'Registro en Garantía'), ('GARANTIA_EXTENDIDA', 'Garantía Extendida'), ('SVAP', 'SVAP (John Deere Protect)'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Certificado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta')),
                ('stock_disponible', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EquipoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie')),
                ('fecha_compra_jd', models.DateField(verbose_name='Fecha de Compra a JD')),
                ('numero_orden_compra', models.CharField(max_length=50, verbose_name='Número de Orden de Compra')),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo de Compra')),
                ('estado', models.CharField(choices=[('EN_STOCK', 'En Stock'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('DEVUELTO', 'Devuelto a JD')], default='EN_STOCK', max_length=20, verbose_name='Estado')),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=200, verbose_name='Ubicación Física')),
                ('año_fabricacion', models.PositiveIntegerField(verbose_name='Año de Fabricación')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.modeloequipo', verbose_name='Modelo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.sucursal', verbose_name='Sucursal')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.tipoequipo', verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Equipo en Stock',
                'verbose_name_plural': 'Equipos en Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VentaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de Venta')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta')),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('certificado_garantia', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'GARANTIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_garantia', to='ventaMaquinarias.certificado')),
                ('certificado_garantia_extendida', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'GARANTIA_EXTENDIDA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_garantia_extendida', to='ventaMaquinarias.certificado')),
                ('certificado_svap', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'SVAP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_svap', to='ventaMaquinarias.certificado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('equipo_stock', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ventaMaquinarias.equipostock', verbose_name='Equipo en Stock')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta de Equipo',
                'verbose_name_plural': 'Ventas de Equipos',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transferencia')),
                ('checklist_completado', models.BooleanField(default=False, verbose_name='Checklist Completado')),
                ('fecha_checklist', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Checklist')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('equipo_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.equipo', verbose_name='Equipo del Cliente')),
                ('usuario_transferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó la Transferencia')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventaMaquinarias.ventaequipo', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Transferencia de Equipo',
                'verbose_name_plural': 'Transferencias de Equipos',
                'ordering': ['-fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStockCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada de Stock'), ('SALIDA', 'Salida de Stock'), ('AJUSTE', 'Ajuste de Stock')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock Anterior')),
                ('stock_nuevo', models.PositiveIntegerField(verbose_name='Stock Nuevo')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ventaMaquinarias.certificado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_certificados', to='ventaMaquinarias.ventaequipo')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock de Certificado',
                'verbose_name_plural': 'Movimientos de Stock de Certificados',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['tipo', 'activo'], name='ventaMaquin_tipo_140d50_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaequipo',
            index=models.Index(fields=['estado', 'fecha_venta'], name='ventaMaquin_estado_7c423d_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaequipo',
            index=models.Index(fields=['cliente', 'fecha_venta'], name='ventaMaquin_cliente_fb0edc_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostockcertificado',
            index=models.Index(fields=['certificado', 'fecha_movimiento'], name='ventaMaquin_certifi_0e47d5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostockcertificado',
            index=models.Index(fields=['tipo_movimiento', 'fecha_movimiento'], name='ventaMaquin_tipo_mo_143d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipostock',
            index=models.Index(fields=['estado', 'sucursal'], name='ventaMaquin_estado_a05f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipostock',
            index=models.Index(fields=['numero_serie'], name='ventaMaquin_numero__303d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipostock',
            index=models.Index(fields=['modelo'], name='ventaMaquin_modelo__e74cb3_idx'),
        ),
    ]
