# Generated by Django 4.2.2 on 2025-07-08 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventaMaquinarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistProcesosJD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_garantias', models.BooleanField(default=False, verbose_name='Registro en Garantías')),
                ('garantia_extendida', models.BooleanField(default=False, verbose_name='Garantía Extendida')),
                ('operations_center', models.BooleanField(default=False, verbose_name='Operations Center')),
                ('svap', models.BooleanField(default=False, verbose_name='SVAP (John Deere Protect)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Actualizó')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_procesos', to='ventaMaquinarias.ventaequipo')),
            ],
            options={
                'verbose_name': 'Checklist de Procesos JD',
                'verbose_name_plural': 'Checklists de Procesos JD',
            },
        ),
    ]
