# Generated by Django 4.2.2 on 2025-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaMaquinarias', '0002_checklistprocesosjd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaequipo',
            name='certificado_garantia',
        ),
        migrations.RemoveField(
            model_name='ventaequipo',
            name='certificado_garantia_extendida',
        ),
        migrations.RemoveField(
            model_name='ventaequipo',
            name='certificado_svap',
        ),
        migrations.AddField(
            model_name='ventaequipo',
            name='certificados',
            field=models.ManyToManyField(blank=True, related_name='ventas', to='ventaMaquinarias.certificado', verbose_name='Certificados Asociados'),
        ),
    ]
