# Generated by Django 4.2.2 on 2025-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaMaquinarias', '0003_remove_ventaequipo_certificado_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipostock',
            name='numero_orden_compra',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Orden de Compra'),
        ),
    ]
