# Generated by Django 4.2.2 on 2024-11-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], max_length=1)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_paquete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('objetivo_paquetes', models.IntegerField()),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PotencialCompraModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencial_anual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potencial Anual USD')),
                ('horas_uso_estimadas', models.IntegerField(verbose_name='Horas de Uso Estimadas Anuales')),
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clientes.modeloequipo')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contacto', models.DateTimeField()),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VENTA_EXITOSA', 'Venta Exitosa'), ('VENTA_PERDIDA', 'Venta Perdida'), ('REPROGRAMADO', 'Reprogramado')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('valor_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('campania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='crm.campania')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
    ]
