# Generated by Django 4.2.2 on 2025-06-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0033_servicio_prioridad'),
        ('clientes', '0007_remove_equipo_estado'),
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('servicios', models.ManyToManyField(related_name='paquetes', to='gestionDeTaller.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='clientes.cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='crm.paqueteservicio')),
            ],
        ),
    ]
