# Generated by Django 4.2.2 on 2025-06-23 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_paqueteservicio_clientepaquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Sugerencia')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('categoria', models.CharField(choices=[('PROCESOS', 'Procesos de Trabajo'), ('EQUIPOS', 'Equipos y Herramientas'), ('SEGURIDAD', 'Seguridad Laboral'), ('CALIDAD', 'Control de Calidad'), ('MANTENIMIENTO', 'Mantenimiento Preventivo'), ('ATENCION_CLIENTE', 'Atención al Cliente'), ('FORMACION', 'Formación y Capacitación'), ('TECNOLOGIA', 'Tecnología y Sistemas'), ('AMBIENTE', 'Ambiente de Trabajo'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_ANALISIS', 'En Análisis'), ('APROBADA', 'Aprobada'), ('IMPLEMENTADA', 'Implementada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Sugerencia')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('fecha_implementacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Implementación')),
                ('respuesta_gerencia', models.TextField(blank=True, null=True, verbose_name='Respuesta de la Gerencia')),
                ('accion_especifica', models.TextField(blank=True, null=True, verbose_name='Acción Específica')),
                ('responsable_implementacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable de Implementación')),
                ('impacto_estimado', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=20, verbose_name='Impacto Estimado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('beneficios_esperados', models.TextField(blank=True, null=True, verbose_name='Beneficios Esperados')),
                ('recursos_necesarios', models.TextField(blank=True, null=True, verbose_name='Recursos Necesarios')),
                ('tiempo_estimado_implementacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo Estimado de Implementación')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
            ],
            options={
                'verbose_name': 'Sugerencia de Mejora',
                'verbose_name_plural': 'Sugerencias de Mejora',
                'ordering': ['-fecha_sugerencia'],
            },
        ),
    ]
