# Generated by Django 4.2.2 on 2025-06-26 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_equipo_estado'),
        ('recursosHumanos', '0013_remove_actividadtrabajo_categoria_facturacion_destinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centroSoluciones', '0001_initial'),
        ('crm', '0004_sugerenciamejora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Campaña')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto')),
                ('objetivo_contactos', models.IntegerField(blank=True, null=True, verbose_name='Objetivo de Contactos')),
                ('objetivo_ventas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Objetivo de Ventas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EmbudoVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('CONTACTO_INICIAL', 'Contacto Inicial'), ('CALIFICACION', 'Calificación'), ('PROPUESTA', 'Propuesta'), ('NEGOCIACION', 'Negociación'), ('CIERRE', 'Cierre'), ('PERDIDO', 'Perdido')], max_length=20, verbose_name='Etapa')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Estimado')),
                ('probabilidad_cierre', models.IntegerField(default=0, verbose_name='Probabilidad de Cierre (%)')),
                ('origen', models.CharField(choices=[('ALERTA_EQUIPO', 'Alerta de Equipo'), ('LEAD_JD', 'Lead John Deere'), ('REFERENCIA', 'Referencia'), ('MARKETING', 'Marketing'), ('SERVICIO_EXISTENTE', 'Servicio Existente'), ('OTRO', 'Otro')], max_length=50, verbose_name='Origen')),
                ('descripcion_negocio', models.TextField(blank=True, verbose_name='Descripción del Negocio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('alerta_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centroSoluciones.alertaequipo', verbose_name='Alerta de Equipo')),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embudos_ventas', to='crm.campana', verbose_name='Campaña')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embudos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('lead_jd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centroSoluciones.leadjohndeere', verbose_name='Lead John Deere')),
            ],
            options={
                'verbose_name': 'Embudo de Ventas',
                'verbose_name_plural': 'Embudos de Ventas',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Contacto')),
                ('tipo_contacto', models.CharField(choices=[('TELEFONO', 'Teléfono'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('VISITA', 'Visita'), ('VIDEO_LLAMADA', 'Video Llamada'), ('REUNION', 'Reunión'), ('PRESENTACION', 'Presentación')], max_length=15, verbose_name='Tipo de Contacto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Contacto')),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('NO_CONTESTA', 'No Contesta'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado'), ('VENTA', 'Venta Realizada'), ('OBJECCION', 'Objeción')], max_length=15, verbose_name='Resultado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proximo_seguimiento', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('embudo_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.embudoventas', verbose_name='Embudo de Ventas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Contacto con Cliente',
                'verbose_name_plural': 'Contactos con Clientes',
                'ordering': ['-fecha_contacto'],
            },
        ),
        migrations.AddIndex(
            model_name='embudoventas',
            index=models.Index(fields=['etapa', 'origen'], name='crm_embudov_etapa_46f097_idx'),
        ),
        migrations.AddIndex(
            model_name='embudoventas',
            index=models.Index(fields=['cliente', 'fecha_ingreso'], name='crm_embudov_cliente_4a6d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='embudoventas',
            index=models.Index(fields=['campana', 'etapa'], name='crm_embudov_campana_3da7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='contactocliente',
            index=models.Index(fields=['cliente', 'fecha_contacto'], name='crm_contact_cliente_f0ec6f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactocliente',
            index=models.Index(fields=['responsable', 'resultado'], name='crm_contact_respons_f2b129_idx'),
        ),
        migrations.AddIndex(
            model_name='contactocliente',
            index=models.Index(fields=['embudo_ventas', 'fecha_contacto'], name='crm_contact_embudo__43dcc6_idx'),
        ),
    ]
