# Generated by Django 4.2.2 on 2025-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_campana_embudoventas_contactocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embudoventas',
            name='valor_cierre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Cierre'),
        ),
    ]
