# Generated by Django 4.2.2 on 2025-07-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_embudoventas_valor_cierre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embudoventas',
            name='probabilidad_cierre',
        ),
    ]
