# Generated by Django 4.2.2 on 2025-07-21 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeTaller', '0051_logcambioitemherramienta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0009_alter_modeloequipo_nombre_alter_modelomotor_nombre_and_more'),
        ('crm', '0007_remove_probabilidad_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbudoChecklistAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('tipo', models.CharField(choices=[('CHECKLIST_ADICIONAL', 'Checklist Adicional'), ('OBSERVACION', 'Observación'), ('MEJORA_PROCEDIMIENTO', 'Mejora de Procedimiento'), ('MANTENIMIENTO_PREVENTIVO', 'Mantenimiento Preventivo'), ('SEGURIDAD', 'Seguridad'), ('CALIDAD', 'Calidad'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('etapa', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EN_ANALISIS', 'En Análisis'), ('PLANIFICADO', 'Planificado'), ('EN_DESARROLLO', 'En Desarrollo'), ('IMPLEMENTADO', 'Implementado'), ('VERIFICADO', 'Verificado'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='IDENTIFICADO', max_length=20, verbose_name='Etapa')),
                ('fecha_identificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Identificación')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('fecha_implementacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Implementación')),
                ('fecha_verificacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Estimado')),
                ('tiempo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo Estimado (horas)')),
                ('recursos_necesarios', models.TextField(blank=True, verbose_name='Recursos Necesarios')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_adicionales', to='clientes.cliente', verbose_name='Cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_adicionales', to='clientes.equipo', verbose_name='Equipo')),
                ('identificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_identificados', to=settings.AUTH_USER_MODEL, verbose_name='Identificado por')),
                ('responsable_implementacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Implementación')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_adicionales', to='gestionDeTaller.servicio', verbose_name='Servicio Relacionado')),
            ],
            options={
                'verbose_name': 'Embudo de Checklist Adicional',
                'verbose_name_plural': 'Embudos de Checklist Adicionales',
                'ordering': ['-fecha_identificacion'],
                'indexes': [models.Index(fields=['etapa', 'prioridad'], name='crm_embudoc_etapa_37ae09_idx'), models.Index(fields=['fecha_identificacion'], name='crm_embudoc_fecha_i_b638c3_idx'), models.Index(fields=['responsable_implementacion'], name='crm_embudoc_respons_325efc_idx')],
            },
        ),
    ]
