# Generated by Django 4.2.2 on 2025-08-18 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_equipo_año_fabricacion'),
        ('crm', '0008_embudochecklistadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='modelo_equipo',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para incluir todos los modelos del tipo seleccionado', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.modeloequipo', verbose_name='Modelo de Equipo'),
        ),
        migrations.AddField(
            model_name='campana',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para incluir todos los tipos de equipos', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.tipoequipo', verbose_name='Tipo de Equipo'),
        ),
    ]
