# Generated by Django 4.2.2 on 2025-08-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_historialfacturacion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historialfacturacion',
            index=models.Index(fields=['pin_equipo'], name='crm_histori_pin_equ_55e905_idx'),
        ),
        migrations.AddIndex(
            model_name='historialfacturacion',
            index=models.Index(fields=['fecha_servicio'], name='crm_histori_fecha_s_a2bbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='historialfacturacion',
            index=models.Index(fields=['cliente'], name='crm_histori_cliente_b5249f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialfacturacion',
            index=models.Index(fields=['equipo'], name='crm_histori_equipo__d0dca0_idx'),
        ),
    ]
