# Generated by Django 4.2.2 on 2025-08-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_equipo_año_fabricacion'),
        ('crm', '0011_historialfacturacion_crm_histori_pin_equ_55e905_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embudoventas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='embudoventas',
            name='origen',
            field=models.CharField(choices=[('ALERTA_EQUIPO', 'Alerta de Equipo'), ('LEAD_JD', 'Lead John Deere'), ('POPS', 'POPS'), ('REFERENCIA', 'Referencia'), ('MARKETING', 'Marketing'), ('SERVICIO_EXISTENTE', 'Servicio Existente'), ('OTRO', 'Otro')], max_length=50, verbose_name='Origen'),
        ),
    ]
