# Generated by Django 4.2.2 on 2025-08-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_embudoventas_cliente_alter_embudoventas_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada')], default='PLANIFICADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='campana',
            name='objetivo_paquetes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Objetivo de Paquetes'),
        ),
        migrations.AddField(
            model_name='campana',
            name='valor_paquete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor del Paquete'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='campania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='crm.campana'),
        ),
        migrations.DeleteModel(
            name='Campania',
        ),
    ]
