# Generated by Django 4.2.2 on 2025-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_campana_estado_campana_objetivo_paquetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactocliente',
            name='imagen_seguimiento',
            field=models.ImageField(blank=True, null=True, upload_to='seguimientos/', verbose_name='Imagen del Seguimiento'),
        ),
        migrations.AlterField(
            model_name='embudoventas',
            name='origen',
            field=models.CharField(choices=[('ALERTA_EQUIPO', 'Alerta de Equipo'), ('LEAD_JD', 'Lead John Deere'), ('POPS', 'POPS'), ('REFERENCIA', 'Referencia'), ('MARKETING', 'Marketing'), ('CAMPAÑA_MARKETING', 'Campaña Marketing'), ('SERVICIO_EXISTENTE', 'Servicio Existente'), ('OTRO', 'Otro')], max_length=50, verbose_name='Origen'),
        ),
    ]
