# Generated by Django 4.2.2 on 2025-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_contactocliente_imagen_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='resultado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CON_RESPUESTA', 'Con Respuesta'), ('PRESUPUESTADO', 'Presupuestado'), ('VENTA_PERDIDA', 'Venta Perdida'), ('VENTA_EXITOSA', 'Venta Exitosa')], max_length=15, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='embudoventas',
            name='etapa',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CON_RESPUESTA', 'Con Respuesta'), ('PRESUPUESTADO', 'Presupuestado'), ('VENTA_PERDIDA', 'Venta Perdida'), ('VENTA_EXITOSA', 'Venta Exitosa')], max_length=20, verbose_name='Etapa'),
        ),
    ]
