# Generated by Django 4.2.2 on 2025-08-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0021_usuario_es_administrativo_especializado_and_more'),
        ('clientes', '0010_alter_equipo_año_fabricacion'),
        ('crm', '0016_update_old_embudo_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='clientes_especificos',
            field=models.ManyToManyField(blank=True, help_text='Seleccionar solo si la segmentación es por clientes específicos', to='clientes.cliente', verbose_name='Clientes Específicos'),
        ),
        migrations.AddField(
            model_name='campana',
            name='provincia',
            field=models.ForeignKey(blank=True, help_text='Seleccionar solo si la segmentación es por provincia', null=True, on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='campana',
            name='tipo_segmentacion',
            field=models.CharField(choices=[('TODOS', 'Todos los Clientes'), ('PROVINCIA', 'Por Provincia'), ('ESPECIFICOS', 'Clientes Específicos'), ('EQUIPOS', 'Por Equipos (Actual)')], default='EQUIPOS', max_length=20, verbose_name='Tipo de Segmentación'),
        ),
    ]
