# Generated by Django 4.2.2 on 2025-08-25 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0010_alter_equipo_año_fabricacion'),
        ('crm', '0017_campana_clientes_especificos_campana_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embudoventas',
            name='objetivo_paquetes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Objetivo de Paquetes'),
        ),
        migrations.AddField(
            model_name='embudoventas',
            name='valor_promedio_paquete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Promedio del Paquete'),
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_contacto', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CLIENTE_RESPONDIO_NO_ACEPTO', 'Cliente respondió pero no aceptó la propuesta'), ('CLIENTE_NO_RESPONDIO_REPROGRAMADO', 'Cliente no respondió y se reprogramó el contacto'), ('CLIENTE_RESPONDIO_REPROGRAMADO', 'Cliente respondió pero se reprogramó el contacto'), ('CLIENTE_ACEPTO_PRESUPUESTO', 'Cliente respondió y aceptó el envío de presupuesto'), ('CLIENTE_ACEPTO_VENTA', 'Cliente respondió y aceptó el presupuesto (venta realizada)'), ('OTRO', 'Otro')], default='PENDIENTE', max_length=50, verbose_name='Estado del Contacto')),
                ('tipo_contacto', models.CharField(choices=[('TELEFONO', 'Teléfono'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('VISITA', 'Visita'), ('VIDEO_LLAMADA', 'Video Llamada'), ('REUNION', 'Reunión'), ('PRESENTACION', 'Presentación')], max_length=20, verbose_name='Tipo de Contacto')),
                ('descripcion_contacto', models.TextField(verbose_name='Descripción del Contacto')),
                ('fecha_proximo_contacto', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Próximo Contacto')),
                ('observaciones_adicionales', models.TextField(blank=True, verbose_name='Observaciones Adicionales')),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='Notificación Enviada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('embudo_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.embudoventas', verbose_name='Embudo de Ventas')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.equipo', verbose_name='Equipo')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CLIENTE_RESPONDIO_NO_ACEPTO', 'Cliente respondió pero no aceptó la propuesta'), ('CLIENTE_NO_RESPONDIO_REPROGRAMADO', 'Cliente no respondió y se reprogramó el contacto'), ('CLIENTE_RESPONDIO_REPROGRAMADO', 'Cliente respondió pero se reprogramó el contacto'), ('CLIENTE_ACEPTO_PRESUPUESTO', 'Cliente respondió y aceptó el envío de presupuesto'), ('CLIENTE_ACEPTO_VENTA', 'Cliente respondió y aceptó el presupuesto (venta realizada)'), ('OTRO', 'Otro')], max_length=50, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CLIENTE_RESPONDIO_NO_ACEPTO', 'Cliente respondió pero no aceptó la propuesta'), ('CLIENTE_NO_RESPONDIO_REPROGRAMADO', 'Cliente no respondió y se reprogramó el contacto'), ('CLIENTE_RESPONDIO_REPROGRAMADO', 'Cliente respondió pero se reprogramó el contacto'), ('CLIENTE_ACEPTO_PRESUPUESTO', 'Cliente respondió y aceptó el envío de presupuesto'), ('CLIENTE_ACEPTO_VENTA', 'Cliente respondió y aceptó el presupuesto (venta realizada)'), ('OTRO', 'Otro')], max_length=50, verbose_name='Estado Nuevo')),
                ('descripcion_cambio', models.TextField(verbose_name='Descripción del Cambio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='crm.oportunidad', verbose_name='Oportunidad')),
                ('responsable_cambio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Cambio')),
            ],
            options={
                'verbose_name': 'Historial de Oportunidad',
                'verbose_name_plural': 'Historial de Oportunidades',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['cliente', 'estado_contacto'], name='crm_oportun_cliente_d0cb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['responsable', 'fecha_proximo_contacto'], name='crm_oportun_respons_73de96_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['embudo_ventas', 'estado_contacto'], name='crm_oportun_embudo__ee2731_idx'),
        ),
    ]
