# Generated by Django 4.2.2 on 2025-08-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_embudoventas_objetivo_paquetes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialoportunidad',
            name='estado_anterior',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CON_RESPUESTA', 'Con Respuesta'), ('PRESUPUESTADO', 'Presupuestado'), ('VENTA_EXITOSA', 'Venta Exitosa'), ('VENTA_PERDIDA', 'Venta Perdida')], max_length=50, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialoportunidad',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CON_RESPUESTA', 'Con Respuesta'), ('PRESUPUESTADO', 'Presupuestado'), ('VENTA_EXITOSA', 'Venta Exitosa'), ('VENTA_PERDIDA', 'Venta Perdida')], max_length=50, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='estado_contacto',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CON_RESPUESTA', 'Con Respuesta'), ('PRESUPUESTADO', 'Presupuestado'), ('VENTA_EXITOSA', 'Venta Exitosa'), ('VENTA_PERDIDA', 'Venta Perdida')], default='PENDIENTE', max_length=50, verbose_name='Estado del Contacto'),
        ),
    ]
