# Generated by Django 4.2.2 on 2025-08-25 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0019_update_estado_contacto_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarea', models.CharField(choices=[('EMAIL_PROXIMO_CONTACTO', 'Email de Próximo Contacto'), ('EMAIL_RECORDATORIO', 'Email de Recordatorio'), ('EMAIL_SEGUIMIENTO', 'Email de Seguimiento')], max_length=30, verbose_name='Tipo de Tarea')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada')),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ejecución')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('max_intentos', models.PositiveIntegerField(default=3, verbose_name='Máximo de Intentos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='crm.oportunidad', verbose_name='Oportunidad')),
            ],
            options={
                'verbose_name': 'Tarea de Oportunidad',
                'verbose_name_plural': 'Tareas de Oportunidad',
                'ordering': ['fecha_programada'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='crm_tareaop_estado_f2a877_idx'), models.Index(fields=['tipo_tarea', 'estado'], name='crm_tareaop_tipo_ta_bce705_idx')],
            },
        ),
    ]
