# Generated by Django 4.2.2 on 2025-08-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0021_usuario_es_administrativo_especializado_and_more'),
        ('crm', '0020_add_tarea_oportunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='ciudad',
            field=models.ForeignKey(blank=True, help_text='Seleccionar solo si la segmentación es por ciudad', null=True, on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='tipo_segmentacion',
            field=models.CharField(choices=[('TODOS', 'Todos los Clientes'), ('PROVINCIA', 'Por Provincia'), ('CIUDAD', 'Por Ciudad'), ('ESPECIFICOS', 'Clientes Específicos'), ('EQUIPOS', 'Por Equipos (Actual)')], default='EQUIPOS', max_length=20, verbose_name='Tipo de Segmentación'),
        ),
    ]
