# Generated by Django 4.2.2 on 2025-08-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_campana_ciudad_alter_campana_tipo_segmentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='categoria_abc',
            field=models.CharField(blank=True, choices=[('A', 'Categoría A (Alto Valor)'), ('B', 'Categoría B (Valor Medio)'), ('C', 'Categoría C (Bajo Valor)'), ('NUEVO', 'Clientes Nuevos'), ('TODAS', 'Todas las Categorías')], help_text='Seleccionar solo si la segmentación es por curva ABC', max_length=10, null=True, verbose_name='Categoría ABC'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='tipo_segmentacion',
            field=models.CharField(choices=[('TODOS', 'Todos los Clientes'), ('PROVINCIA', 'Por Provincia'), ('CIUDAD', 'Por Ciudad'), ('ABC', 'Por Curva ABC'), ('ESPECIFICOS', 'Clientes Específicos'), ('EQUIPOS', 'Por Equipos (Actual)')], default='EQUIPOS', max_length=20, verbose_name='Tipo de Segmentación'),
        ),
    ]
