# Generated by Django 4.2.2 on 2024-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AddField(
            model_name='tarifamanoobra',
            name='tipo_servicio',
            field=models.CharField(choices=[('TALLER', 'Trabajo en Taller'), ('CAMPO', 'Trabajo en Campo')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
