# Generated by Django 4.2.2 on 2024-11-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0002_alter_ciudad_options_tarifamanoobra_tipo_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramientaespecial',
            name='estante',
        ),
    ]
