# Generated by Django 4.2.2 on 2024-11-04 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0003_remove_herramientaespecial_estante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.provincia', verbose_name='Provincia'),
            preserve_default=False,
        ),
    ]
