# Generated by Django 4.2.2 on 2025-03-03 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0004_ciudad_provincia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohorastecnico',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Registro de Horas Técnico', 'verbose_name_plural': 'Registros de Horas Técnicos'},
        ),
        migrations.AlterField(
            model_name='registrohorastecnico',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='¿Aprobado?'),
        ),
        migrations.AlterField(
            model_name='registrohorastecnico',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'GERENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AlterField(
            model_name='registrohorastecnico',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción de la Actividad'),
        ),
    ]
