# Generated by Django 4.2.2 on 2025-03-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0005_alter_registrohorastecnico_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohoratrabajo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='tipohoratrabajo',
            name='actividad',
            field=models.CharField(choices=[('INGRESOS', [('SERVICIO_TALLER', 'Servicio Taller'), ('SERVICIO_REMOTO', 'Servicio Remoto'), ('SERVICIO_CAMPO', 'Servicio Campo'), ('IDA_VUELTA_CAMPO', 'Ida/Vuelta a Campo')]), ('SIN_INGRESOS', [('LIMPIEZA', 'Limpieza'), ('CAPACITACION', 'Capacitación'), ('SIN_TRABAJO', 'Sin Trabajo Asignado'), ('PREP_SALIDA_CAMPO', 'Preparación para Salida al Campo'), ('PREP_TRABAJO_TALLER', 'Preparación para Trabajo en Taller'), ('ORG_BOX_HERRAMIENTAS', 'Organización de Box/Herramientas'), ('AUSENCIA', 'Ausencia'), ('VACACIONES', 'Vacaciones')])], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
