# Generated by Django 4.2.2 on 2025-03-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0006_remove_tipohoratrabajo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipohoratrabajo',
            options={'verbose_name': 'Tipo de Hora Trabajo', 'verbose_name_plural': 'Tipos de Horas Trabajo'},
        ),
        migrations.RemoveField(
            model_name='tipohoratrabajo',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='tipohoratrabajo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tipohoratrabajo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipohoratrabajo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tipohoratrabajo',
            name='categoria',
            field=models.CharField(choices=[('PRODUCTIVA', 'Horas con Ingresos'), ('NO_PRODUCTIVA', 'Horas sin Ingresos')], default=1, max_length=15, unique=True, verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActividadTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Actividad')),
                ('tipo_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.tipohoratrabajo', verbose_name='Tipo de Hora')),
            ],
            options={
                'verbose_name': 'Actividad de Trabajo',
                'verbose_name_plural': 'Actividades de Trabajo',
                'ordering': ['tipo_hora', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='registrohorastecnico',
            name='tipo_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.actividadtrabajo'),
        ),
    ]
