# Generated by Django 4.2.2 on 2025-03-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0007_alter_tipohoratrabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohoratrabajo',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipohoratrabajo',
            name='categoria',
            field=models.CharField(choices=[('PRODUCTIVA', 'Horas con Ingresos'), ('NO_PRODUCTIVA', 'Horas sin Ingresos')], max_length=15, verbose_name='Categoría'),
        ),
    ]
