# Generated by Django 4.2.2 on 2025-03-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0008_tipohoratrabajo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadtrabajo',
            name='tipo_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='recursosHumanos.tipohoratrabajo', verbose_name='Tipo de Hora'),
        ),
        migrations.AlterField(
            model_name='registrohorastecnico',
            name='tipo_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursosHumanos.actividadtrabajo', verbose_name='Actividad'),
        ),
    ]
