# Generated by Django 4.2.2 on 2025-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0009_alter_actividadtrabajo_tipo_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadtrabajo',
            options={'verbose_name': 'Actividad de Trabajo', 'verbose_name_plural': 'Actividades de Trabajo'},
        ),
        migrations.RemoveField(
            model_name='actividadtrabajo',
            name='tipo_hora',
        ),
        migrations.AddField(
            model_name='actividadtrabajo',
            name='categoria_facturacion',
            field=models.CharField(choices=[('FACTURABLE', 'Facturable'), ('NO_FACTURABLE', 'No facturable, Ineficiente')], default=1, max_length=15, verbose_name='Categoría de Facturación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadtrabajo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actividadtrabajo',
            name='disponibilidad',
            field=models.CharField(choices=[('DISPONIBLE', 'Horas disponibles'), ('NO_DISPONIBLE', 'Horas no disponibles')], default=1, max_length=15, verbose_name='Disponibilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadtrabajo',
            name='genera_ingreso',
            field=models.CharField(choices=[('INGRESO', 'Genera Ingreso'), ('NO_INGRESO', 'No genera Ingreso')], default=1, max_length=15, verbose_name='Generación de Ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividadtrabajo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='TipoHoraTrabajo',
        ),
    ]
