# Generated by Django 4.2.2 on 2025-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0010_alter_actividadtrabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadtrabajo',
            name='categoria_facturacion_destinatario',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('GARANTIA', 'Garantía')], default=1, max_length=15, verbose_name='Categoría de Facturación Destinatario'),
            preserve_default=False,
        ),
    ]
