# Generated by Django 4.2.2 on 2025-05-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0011_actividadtrabajo_categoria_facturacion_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadtrabajo',
            name='categoria_facturacion',
            field=models.CharField(blank=True, choices=[('FACTURABLE', 'Facturable'), ('NO_FACTURABLE', 'No facturable, Ineficiente')], max_length=15, null=True, verbose_name='Categoría de Facturación'),
        ),
        migrations.AlterField(
            model_name='actividadtrabajo',
            name='categoria_facturacion_destinatario',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('GARANTIA', 'Garantía')], max_length=15, null=True, verbose_name='Categoría de Facturación Destinatario'),
        ),
        migrations.AlterField(
            model_name='actividadtrabajo',
            name='genera_ingreso',
            field=models.CharField(blank=True, choices=[('INGRESO', 'Genera Ingreso'), ('NO_INGRESO', 'No genera Ingreso')], max_length=15, null=True, verbose_name='Generación de Ingreso'),
        ),
    ]
