# Generated by Django 4.2.2 on 2025-05-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0012_alter_actividadtrabajo_categoria_facturacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadtrabajo',
            name='categoria_facturacion_destinatario',
        ),
    ]
