# Generated by Django 4.2.2 on 2025-07-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0002_sesioncronometro'),
        ('recursosHumanos', '0013_remove_actividadtrabajo_categoria_facturacion_destinatario'),
    ]

    operations = [
    ]
