# Generated by Django 4.2.2 on 2025-07-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0014_merge_20250715_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCronometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('CRONOMETRO_ACTIVO', 'Cronómetro Activo'), ('CRONOMETRO_OLVIDADO', 'Cronómetro Olvidado'), ('FINALIZACION_AUTOMATICA', 'Finalización Automática')], max_length=25, verbose_name='Tipo de Alerta')),
                ('destinatarios', models.JSONField(help_text='Lista de emails a los que se envió la alerta', verbose_name='Destinatarios')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto del Email')),
                ('mensaje', models.TextField(verbose_name='Mensaje Enviado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursosHumanos.sesioncronometro', verbose_name='Sesión de Cronómetro')),
            ],
            options={
                'verbose_name': 'Alerta de Cronómetro',
                'verbose_name_plural': 'Alertas de Cronómetros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
