# Generated by Django 4.2.2 on 2025-07-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0015_alertacronometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursales_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Sucursales adicionales para gerentes (opcional)', related_name='usuarios_adicionales', to='recursosHumanos.sucursal', verbose_name='Sucursales Adicionales'),
        ),
    ]
