# Generated by Django 4.2.2 on 2025-07-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0016_usuario_sucursales_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadtrabajo',
            name='requiere_servicio',
            field=models.BooleanField(default=False, help_text='Si está marcado, esta actividad siempre requiere asociar un servicio', verbose_name='Requiere Asociación de Servicio'),
        ),
    ]
