# Generated by Django 4.2.2 on 2025-07-31 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0018_marcar_actividades_requieren_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('ENFERMEDAD', 'Enfermedad'), ('PERSONAL', 'Personal'), ('MATERNIDAD', 'Maternidad'), ('PATERNIDAD', 'Paternidad'), ('CAPACITACION', 'Capacitación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Permiso')),
                ('motivo', models.TextField(verbose_name='Motivo del Permiso')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observaciones_aprobacion', models.TextField(blank=True, verbose_name='Observaciones de Aprobación')),
                ('justificativo', models.FileField(blank=True, null=True, upload_to='permisos/justificativos/', verbose_name='Justificativo')),
                ('descripcion_justificativo', models.CharField(blank=True, max_length=200, verbose_name='Descripción del Justificativo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_ausencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Ausencia',
                'verbose_name_plural': 'Permisos de Ausencia',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='recursosHum_usuario_5be7be_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='recursosHum_fecha_i_0b6145_idx'), models.Index(fields=['estado', 'fecha_solicitud'], name='recursosHum_estado_1d78b2_idx')],
            },
        ),
    ]
