# Generated by Django 4.2.2 on 2025-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0019_permisoausencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausencia',
            name='tipo_permiso',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('ENFERMEDAD', 'Enfermedad'), ('PERSONAL', 'Personal'), ('LICENCIA_ESPECIAL', 'Licencia Especial'), ('CAPACITACION', 'Capacitación'), ('COMPENSACION', 'Compensación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Permiso'),
        ),
    ]
