# Generated by Django 4.2.2 on 2025-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0020_alter_permisoausencia_tipo_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_administrativo_especializado',
            field=models.BooleanField(default=False, help_text='Marcar si el usuario administrativo tiene una especialización específica', verbose_name='¿Es administrativo especializado?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especializacion_admin',
            field=models.CharField(blank=True, choices=[('RRHH', 'Recursos Humanos'), ('CONTABLE', 'Contable'), ('CAJERO', 'Cajero'), ('SERVICIOS', 'Servicios'), ('REPUESTOS', 'Repuestos'), ('GENERAL', 'General')], help_text='Especialización para usuarios administrativos', max_length=20, null=True, verbose_name='Especialización Administrativa'),
        ),
    ]
